apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: RTCclusterregistry.azurecr.io/project:latest  # Utilisez l'image ACR
        ports:
        - containerPort: 80
        volumeMounts:
        - name: code-volume
          mountPath: /var/www/html
        - name: db-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: code-volume
        hostPath:
          path: ./Code 
      - name: db-volume
        hostPath:
          path: ./Database  
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache-service
spec:
  selector:
    app: php-apache
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
